language: emacs-lisp

env:
  matrix:
    - EMACS=emacs23 ORG=maint
    - EMACS=emacs23 ORG=master
    - EMACS=emacs24 ORG=maint
    - EMACS=emacs24 ORG=master

before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq $EMACS

  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH="/home/travis/.cask/bin:$PATH"
  - cask --version

  - git clone --branch $ORG --depth 1 git://orgmode.org/org-mode.git

script:
  - emacs --version
