language: emacs-lisp

env:
  matrix:
    - EMACS=emacs23
    - EMACS=emacs24

before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq $EMACS

script:
  - emacs --version
