# `emacs-lisp' isn't supported and fallback to `ruby'
language: emacs-lisp

env:
  matrix:
    - EMACS=emacs23 ORG_BRANCH=maint
    - EMACS=emacs23 ORG_BRANCH=master
    - EMACS=emacs24 ORG_BRANCH=maint
    - EMACS=emacs24 ORG_BRANCH=master

before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq $EMACS

  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH="/home/travis/.cask/bin:$PATH"
  - cask --version

  - git clone --branch $ORG_BRANCH --depth 1 git://orgmode.org/org-mode.git && (cd org-mode && make autoloads)

script:
  - emacs --version
  - pwd
