# `emacs-lisp' isn't supported and fallback to `ruby'
language: emacs-lisp

env:
  global:
    - ORG_REPO=git://orgmode.org/org-mode.git
    - ORG_DIR=org-mode

  matrix:
    - EMACS=emacs23 ORG_BRANCH=maint
    - EMACS=emacs23 ORG_BRANCH=master
    - EMACS=emacs24 ORG_BRANCH=maint
    - EMACS=emacs24 ORG_BRANCH=master

before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq $EMACS

  - git clone --branch $ORG_BRANCH $ORG_REPO && (cd org-mode && echo "autoloads:" > local.mk && make)

script:
  - emacs -Q --script test-runner.el
